name: Matrix workflow
on: push
jobs:
    Build:
        continue-on-error: true
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [16, 18]
                exlude:
                    - os: windows-latest
                      node-version: 16         
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci